// Generated by CoffeeScript 1.6.1
/*
Main script file for jszpila.github.com
Author: Jan Szpila
*/(function(){$(function(){var e,t;e=(new Date).getHours();t="dark";e>6&&e<18&&(t="light");$("body").addClass(t);$("nav a").tooltip({placement:"bottom"});return $("#EmailLink").click(function(e){var t,n,r,i;e.preventDefault();t=null;r=[19,28,35,25,18,21,10,"@",16,22,10,18,21,".",12,24,22];n=0;i=r.length;while(n<i){t=r[n];typeof t=="number"&&(r[n]=t.toString(36));n++}window.open(["mailto:",r.join(""),"?subject=Hi%2C%20Jan!"].join(""));return!1})})}).call(this);