// Generated by CoffeeScript 1.6.3
/*
Main script file for jszpila.github.com
Author: Jan Szpila
*/


(function() {
  $(function() {
    return $('#EmailLink').click(function(e) {
      var part, parts, _i, _len;
      e.preventDefault();
      parts = [19, 28, 35, 25, 18, 21, 10, '@', 16, 22, 10, 18, 21, '.', 12, 24, 22];
      for (_i = 0, _len = parts.length; _i < _len; _i++) {
        part = parts[_i];
        if (typeof part === 'number') {
          part = part.toString(36);
        }
      }
      window.open(['mailto:', parts.join(''), '?subject=Hi%2C%20Jan!'].join(''));
      return false;
    });
  });

}).call(this);
